version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - app-network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: mugdots
      MONGO_INITDB_ROOT_PASSWORD: testeDB
    ports:
      - 27017:27017
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redisCache
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
