version: "3.9"

services:
  app1:
    build: ./frontend
    container_name: app1
    environment:
      - APP_NAME=App1
    ports:
      - 3001:3000
    networks:
      - app-network

  app2:
    build: ./frontend
    container_name: app2
    environment:
      - APP_NAME=App2
    ports:
      - 3002:3000
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - 5000:5000
    networks:
      - app-network

#  redis:
#    image: redis:latest
#    container_name: redisCache
#    ports:
#      - 6379:6379
#    networks:
#      - app-network
  
  nginx:
    container_name: nginx
    image: nginx
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
