version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - app-network


  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5050:5050
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redisCache
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
